// =============================================================================
// Header.h
// -----------------------------------------------------------------------------
// Shared protocol model + public interfaces for Protocol 5 simulation modules.
//
// PURPOSE
//   - Defines Frame/Ack data structures.
//   - Defines protocol/channel constants.
//   - Declares sender/receiver interfaces used by main/channel.
//
// TEAM CONTRACT
//   - Keep declarations synchronized with Sender.cpp / Receiver.cpp.
//   - Any signature change here requires updating all call sites.
//   - This header should remain implementation-free (declarations only).
// =============================================================================

#ifndef HEADER_H  // Starts include guard to prevent duplicate inclusion.
#define HEADER_H  // Defines include guard macro.

// Represents one data frame generated by the sender.
struct Frame
{
    int seq_num;  // Sequence number carried in the frame header.
};

// Represents one ACK generated by the receiver.
struct Ack
{
    int ack_num;  // Cumulative ACK number.
};

// Maximum number of unacknowledged frames allowed in sender window.
const int WINDOW_SIZE = 4;
// Sequence-number space size used for wraparound arithmetic.
const int MAX_SEQ = 256;
// One-way propagation delay in milliseconds for both frames and ACKs.
const int PROP_DELAY = 250;

// Sends one new frame if sender window has capacity.
bool send_frame(int current_time);
// Processes one cumulative ACK delivered to sender.
void receive_ack(int ack_num, int current_time);
// Checks sender timeout and retransmits outstanding frames if needed.
void check_timeout(int current_time);
// Exposes sender base sequence number.
int get_sender_base();
// Exposes sender next sequence number.
int get_sender_next_seq();
// Reinitializes sender state for a fresh simulation run.
void reset_sender();

// Processes one incoming frame at receiver side.
void receive_frame(Frame frame, int current_time);
// Reinitializes receiver state for a fresh simulation run.
void reset_receiver();

#endif  // Ends include guard.
