// =============================================================================
// protocol5_main.cpp
// -----------------------------------------------------------------------------
// Protocol 5 simulation driver (CLI entry point).
//
// PURPOSE
//   - Wires sender, receiver, and channel modules.
//   - Runs a discrete-time simulation loop.
//   - Emits execution trace suitable for screenshots/reports.
//
// INPUT (CLI)
//   argv[1]: frame loss percent   (double, default 0)
//   argv[2]: ACK loss percent     (double, default 0)
//   argv[3]: total data frames    (int,    default 12)
//   argv[4]: max simulation time  (int ms, default 8000)
//
// OUTPUT
//   - Console trace of send/receive/ACK/timeout events.
//   - Completion line when all frames are ACKed.
//
// TEAM CONTRACT
//   - Keep this file free of protocol-state internals (state lives in modules).
//   - If completion condition changes, keep assignment screenshots reproducible.
//   - If CLI shape changes, update report instructions and teammates' commands.
// =============================================================================

#include <cstdlib>    // Provides atof/atoi for parsing CLI arguments.
#include <iostream>   // Provides std::cout and std::endl for console output.
#include "Header.h"   // Sender/receiver public API and protocol constants.
#include "Channel.h"  // Channel configuration and event-processing API.

using namespace std;  // Keeps example implementation concise.

// Entry point that configures and runs one simulation instance.
int main(int argc, char* argv[])
{
    // Default frame loss percentage when not passed by CLI.
    double frame_loss_percent = 0.0;
    // Default ACK loss percentage when not passed by CLI.
    double ack_loss_percent = 0.0;
    // Default number of data frames generated by the application layer.
    int total_frames = 12;
    // Default upper bound on simulated time.
    int max_time_ms = 8000;
    // Fixed time granularity for discrete simulation steps.
    const int STEP_MS = 50;

    // Parse optional CLI argument #1 (frame loss percentage).
    if (argc > 1)
        frame_loss_percent = atof(argv[1]);
    // Parse optional CLI argument #2 (ACK loss percentage).
    if (argc > 2)
        ack_loss_percent = atof(argv[2]);
    // Parse optional CLI argument #3 (total frames).
    if (argc > 3)
        total_frames = atoi(argv[3]);
    // Parse optional CLI argument #4 (simulation horizon in ms).
    if (argc > 4)
        max_time_ms = atoi(argv[4]);

    // Ensure sender state starts clean for this run.
    reset_sender();
    // Ensure receiver state starts clean for this run.
    reset_receiver();

    // Register receiver callback for frame deliveries.
    register_receiver(receive_frame);
    // Register sender callback for ACK deliveries.
    register_sender_ack(receive_ack);
    // Apply frame loss probability to channel model.
    set_frame_loss_probability(frame_loss_percent);
    // Apply ACK loss probability to channel model.
    set_ack_loss_probability(ack_loss_percent);

    // Print simulation banner.
    cout << "=== Protocol 5 (Go-Back-N style) Simulation ===" << endl;
    // Print active run parameters.
    cout << "frame_loss=" << frame_loss_percent << "%, ack_loss=" << ack_loss_percent
         << "%, frames=" << total_frames << ", max_time_ms=" << max_time_ms << endl;

    // Tracks how many frames the application has offered to sender.
    int app_next_frame = 0;
    // Tracks whether run reached full successful completion.
    bool completed = false;

    // Drive simulation clock from t=0 to max_time_ms.
    for (int t = 0; t <= max_time_ms; t += STEP_MS)
    {
        // Synchronize channel module with current clock tick.
        set_channel_time(t);

        // Keep sending new frames while sender window can accept more.
        while (app_next_frame < total_frames)
        {
            // Stop when sender window is full.
            if (!send_frame(t))
                break;
            // Record that one additional application frame was issued.
            app_next_frame++;
        }

        // Process in-flight frame/ACK deliveries for this tick.
        process_channel(t);
        // Process timeout and possible retransmissions for this tick.
        check_timeout(t);

        // Completion: all frames generated and all outstanding frames ACKed.
        if (app_next_frame == total_frames && get_sender_base() == get_sender_next_seq())
        {
            // Print successful completion line.
            cout << "t=" << t << ": All " << total_frames << " frames delivered and acknowledged." << endl;
            // Mark simulation as completed.
            completed = true;
            // Exit simulation loop.
            break;
        }
    }

    // Emit diagnostics if run timed out before complete delivery/ACK.
    if (!completed)
    {
        // Print generic timeout/unfinished notice.
        cout << "Simulation ended before full completion." << endl;
        // Print sender/application progress snapshot for troubleshooting.
        cout << "sender_base=" << get_sender_base()
             << ", sender_next_seq=" << get_sender_next_seq()
             << ", app_sent=" << app_next_frame << endl;
    }

    // Return success exit code.
    return 0;
}
